# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    TWITCH_CLIENT_ID: "%env(TWITCH_CLIENT_ID)%"
    TWITCH_ACCESS_TOKEN: "%env(TWITCH_ACCESS_TOKEN)%"

    twitch.categories:
        TOTK: [512998, 1981388235]
        Skyrim: [30028, 1050003477, 1258270417]
        Isaac: [32207, 94073, 201557326, 436344698, 906830759, 1414860634]

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"

    App\Service\TwitchCollector:
        arguments:
            $clientId: "%TWITCH_CLIENT_ID%"
            $accessToken: "%TWITCH_ACCESS_TOKEN%"
            $outputDir: "%kernel.project_dir%/data"

    App\Command\TwitchCollectCommand:
        arguments:
            $categories: "%twitch.categories%"
